services:
  privatefrp-agent:
    image: ghcr.io/andyishereboi/privatefrp-agent:latest
    env_file:
      - ./agent.env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
