services:
  server:
    image: ghcr.io/andyishereboi/privatefrp-server:latest
    ports:
      - "7000:7000"
      - "8089:8089"
    environment:
      - SERVER_PORT=7000
      - DASHBOARD_PORT=8089
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DATABASE_PATH=./data/privatefrp.db
      - TLS_CERT=
      - TLS_KEY=
    volumes:
      - ./data:/app/data
