services:
  privatefrp-server:
    image: ghcr.io/andyishereboi/privatefrp-server:latest
    network_mode: host
    env_file:
      - ./env.example
    volumes:
      - ./data:/app/data
      - ./data/certs:/app/certs:ro
    restart: unless-stopped